### ISSUE TITLE
搭好后 可以出现黄标  但是不能硬解,恢复备份时提示premier失效

### ISSUE THREAD

**Issue by aronyfhj** [fejich/docker-embyhack#8]
搭好后 可以出现黄标  但是不能硬解,恢复备份时提示premier失效

**Comment by fejich** [comment]
![2024 12 06](https://github.com/user-attachments/assets/76d7e500-b726-4d9d-9921-b705818a51a3)
群辉DS918，使用项目文件全新部署
测试下来是正常的

Emby Server 版本 4.8.10.0

**Comment by aronyfhj** [comment]
> ![2024 12 06](https://private-user-images.githubusercontent.com/12195592/393115151-76d7e500-b726-4d9d-9921-b705818a51a3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0Njc5MDcsIm5iZiI6MTczMzQ2NzYwNywicGF0aCI6Ii8xMjE5NTU5Mi8zOTMxMTUxNTEtNzZkN2U1MDAtYjcyNi00ZDlkLTk5MjEtYjcwNTgxOGE1MWEzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA2NDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZjA0N2RkOGJlMDNiNDgxYTdjOTg1NGZmNzFjNWZkNWUxY2Y2NGMyODMzNTE5ZWY3MWIxZGNmMzhmODFhZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CYINKN0f8laoFarwGsncFZunX4wyKGrhSAhdYzCFpwM) 群辉DS918，使用项目文件全新部署 测试下来是正常的
> 
> Emby Server 版本 4.8.10.0

部署后还需要什么别的操作吗?
我下拉脚本后
修改nginx 路径为docker目录下对应目录
修改emby 路径为docker目录下对应目录
并把对应的证书文件复制到对应的目录里


```
version: "2.1"
services:
  nginx:
    image: linuxserver/nginx
    container_name: mb3admin.com #两个容器间互联，实现免改 hosts/DNS 指定 emby 服务端访问本地伪造的 mb3admin.com 网站
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /volume6/docker/nginx:/config #nginx 的配置目录，已经部署好伪造证书与 emby 授权的响应
#    ports:
#      - 443:443
#单纯破解与该容器互联的 emby 服务端情况下，无需映射 https 的 443 端口出来
    restart: unless-stopped

  emby:
    image: linuxserver/emby
    depends_on:
      - nginx
    container_name: emby1
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - /volume6/docker/emby1/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt #将添加了 伪造CA证书 的信任列表，
替换到容器内
      - /volume6/docker/emby1/emby-ca-certificates.crt:/app/emby/etc/ssl/certs/ca-certificates.crt ##将添加了 伪造CA证
书 的信任列表，替换到容器内（emby 的 c# 环境）
      - /volume6/docker/emby1:/config #emby 的配置目录
```
